# Bedrock
quarkus.langchain4j.bedrock.chat-model.model-id=anthropic.claude-3-sonnet-20240229-v1:0
quarkus.langchain4j.bedrock.aws.region=us-east-1

# Ollama configuration
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.chat-model.model-name=llama3
quarkus.langchain4j.ollama.timeout=60s

quarkus.langchain4j.amazon-bedrock.aws.access-key-id=YOUR_KEY
quarkus.langchain4j.amazon-bedrock.aws.secret-access-key=YOUR_SECRET

bedrock.kb.id=KB1234567890ABC
# MSK Kafka
kafka.bootstrap.servers=MSK_BOOTSTRAP:9092

mp.messaging.outgoing.recipe-requests.connector=smallrye-kafka
mp.messaging.outgoing.recipe-requests.topic=recipe-requests
mp.messaging.outgoing.recipe-requests.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.incoming.recipe-responses.connector=smallrye-kafka
mp.messaging.incoming.recipe-responses.topic=recipe-responses
mp.messaging.incoming.recipe-responses.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.outgoing.recipe-search-out.connector=smallrye-kafka
mp.messaging.outgoing.recipe-search-out.topic=recipe-search-events
mp.messaging.outgoing.recipe-search-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer